services:
  - type: web
    name: steilar
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_APP_NAME
        value: Steilar
